apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmedik
  labels:
    app: bookmedik
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookmedik
      tier: frontend
  template:
    metadata:
      labels:
        app: bookmedik
        tier: frontend
    spec:
      containers:
      - name: bookmedik
        image: mariajesusbp/bookmedik:v3
        env:
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: cm-mariadb
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secreto-mariadb
                key: DATABASE_PASSWORD
          - name: HOST
            value: mariadb
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: cm-mariadb
                key: bbdd
        ports:
          - name: http-server
            containerPort: 80
